### ISSUE TITLE
Can't handle numbers in scientific Format

### ISSUE THREAD

**Issue by nicosurf** [kuleszdl/SIFEI#134]
It appears, that teh XML Wrapper xcan't handle numbers in scientific Format. 
The moment one number appears in this format (`a*b^c`) an exception is thrown, the scan is apported and no cellmarkings are drawn.

**Comment by kuleszdl** [comment]
Is the wrapper on the SIF or SIFEI side causing this issue?

**Comment by friederschueler** [comment]
Fixed in new SIFCore, but numbers will be displayed in non scientific format, which can lead to really big numbers. This will fix all numbers in the inspectionReport generated by SIFCore.

We could think about an automatic conversion to the scintific format if the number is longer than x characters.

**Comment by kuleszdl** [comment]
To be continued in #141 - closing this one.
